#create a post
POST http://localhost:4500/posts/createpost
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "image": "https://cdn.pixabay.com/photo/2023/08/20/20/03/planes-8203121_1280.jpg",
    "body": "sunday test 2",
    "tagged": ""
}


###
#edit a post
PUT http://localhost:4500/posts/editpost
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "post_id": "5c7f8faa-a07e-44da-9094-ea075a391ac9",
    "body": "edited",
    "tagged": ""
}


###
#delete a post
PUT http://localhost:4500/posts/deletepost/5c7f8faa-a07e-44da-9094-ea075a391ac9
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4"
}


###
#like post
POST http://localhost:4500/posts/likepost
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "post_id": "90af0c8b-7ee7-48a8-a494-927c82598db3"
}



###
#unlike post
POST http://localhost:4500/posts/unlikepost
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "post_id": "90af0c8b-7ee7-48a8-a494-927c82598db3"
}



###
#like sub comment
POST http://localhost:4500/posts/likeSubcomment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "subcomment_id": "1"
}



###
#unlike sub comment
POST http://localhost:4500/posts/unlikeSubcomment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "subcomment_id": "1"
}



###
#like comment
POST http://localhost:4500/posts/likeComment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "comment_id": "1"
}



###
#unlike comment
POST http://localhost:4500/posts/unlikeComment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "comment_id": "1"
}




###
#comment on post
POST http://localhost:4500/posts/createComment
Content-Type: application/json

{
    "post_id": "90af0c8b-7ee7-48a8-a494-927c82598db3",
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "body": "Sunday test 1 indeed"
}



###
#update comment
POST http://localhost:4500/posts/updateComment
Content-Type: application/json

{
    "comment_id": "1",
    "post_id": "90af0c8b-7ee7-48a8-a494-927c82598db3",
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "body": "comment updated bruv on sunday test indeed"
}


###
#fetch single post
GET  http://localhost:4500/posts/viewSinglePost/90af0c8b-7ee7-48a8-a494-927c82598db3
Content-Type: application/json



###
#create subcomment 
POST  http://localhost:4500/posts/createSubComment
Content-Type: application/json

{
    "comment_id": "1",
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "body": "subcoment sunday init"
}



###
#update subcomment 
POST  http://localhost:4500/posts/updateSubcomment
Content-Type: application/json

{
    "subcomment_id": "1",
    "comment_id": "1",
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "body": "subcoment sunday init updated"
}




###
#rank posts
GET  http://localhost:4500/posts/rankPostEngagement
Content-Type: application/json



###
#fetch posts based on engagement perfomance
GET  http://localhost:4500/posts/fetchPostsBasedOnPerfomance
Content-Type: application/json




###
#fetch recent posts
GET  http://localhost:4500/posts/fetchRecentPosts
Content-Type: application/json



###
#register a user
POST http://localhost:4500/posts/registerUser
Content-Type: application/json

{
    "first_name": "Ben",
    "last_name": "Siloma",
    "username": "silomaben",
    "email": "siloma@gmail.com",
    "password": "plokijuhy",
    "profile_pic_url": "https://cdn.pixabay.com/photo/2023/08/20/20/03/planes-8203121_1280.jpg"
}


