###
#register a user
POST http://localhost:4500/auth/register
Content-Type: application/json

{
    "first_name": "success",
    "last_name": "test",
    "username": "Successfully",
    "email": "successfully@gmail.com",
    "password": "plokijuhy",
    "profile_pic_url": "https://cdn.pixabay.com/photo/2023/08/20/20/03/planes-8203121_1280.jpg"
}


### 
#login a user
POST http://localhost:4500/auth/login
Content-Type: application/json

{
    "credential": "successfully@gmail.com", 
    "passcode": "plokijuhy"
}



###
#update user info
POST http://localhost:4500/user/edit-profile
Content-Type: application/json

{
    "user_id": "234a7d37-d622-47da-b41a-e314cd619b7e",
    "first_name": "test",
    "last_name": "failednot",
    "username": "failtest",
    "profile_pic_url": "https://cdn.pixabay.com/photo/2023/08/20/20/03/planes-8203121_1280.jpg",
    "bio":"Like batman, I fight bugs in the dark night",
    "linkedin_url":"",
    "facebook_url":"",
    "website_url":"",
    "instagram_url":"",
    "twitter_url":""
}


###
# view user
POST http://localhost:4500/user/view-user
Content-Type: application/json

{
    "me_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "them_username": "admin"
}


###
# follow user
POST http://localhost:4500/user/follow
Content-Type: application/json

{
    "follower_id":  "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "followed_id": "234a7d37-d622-47da-b41a-e314cd619b7e"
}



###
# unfollow user
POST http://localhost:4500/user/unfollow
Content-Type: application/json

{
    "unfollower_id": "39cd9427-42c8-44e1-b436-20612b21d144",
    "unfollowed_id": "234a7d37-d622-47da-b41a-e314cd619b7e"
}



###
#forgot password
POST http://localhost:4500/auth/forgot-password
Content-Type: application/json

{
    "email": "kaybernard449@gmail.com"
}


###
#verify token
GET http://localhost:4500/auth/verify-token/da3eaa08faf81db85d92516f5570b350b58766d7/kaybernard449@gmail.com
Content-Type: application/json



###
# reset password
POST http://localhost:4500/auth/reset-password
Content-Type: application/json

{
    "email": "kaybernard449@gmail.com",
    "password": "plokijuhy"
}


###
#deactivate a user
POST http://localhost:4500/auth/deactivate
Content-Type: application/json

{
    "user_id": "e2793b07-bd4d-42c7-ad97-9dfb122f8ff9",
    "password": "plokijuhy"
}


###
#activate a user
POST http://localhost:4500/auth/activate
Content-Type: application/json

{
    "email": "kaybernard449@gmail.com",
    "password": "plokijuhy"
}






###
#create a post
POST http://localhost:4500/posts/createpost
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2OTQ2MjA1MjIsImV4cCI6MTY5NDYyNDEyMn0.vNlRP5t9FHwjlr8AMJ63u-JiAYz1lPe04lNXTxrKnxM

{
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "image": "https://cdn.pixabay.com/photo/2023/08/20/20/03/planes-8203121_1280.jpg",
    "body": "is jwt expired",
    "tagged": ""
}


###
#fetch single post
POST  http://localhost:4500/posts/viewSinglePost/c21376b4-56b9-4df1-9428-17eeaf2ac1b2
Content-Type: application/json

{
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac"
}



###
#fetch posts based on engagement perfomance
GET  http://localhost:4500/posts/fetchPostsBasedOnPerfomance/39cd9427-42c8-44e1-b436-20612b21d144
Content-Type: application/json



###
#fetch recent posts
GET  http://localhost:4500/posts/fetchRecentPosts
Content-Type: application/json




###
#fetch single user post
POST  http://localhost:4500/posts/fetchSingleUserPosts/admin
Content-Type: application/json

{
     "viewer_userId": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac"
}




###
#edit a post
PUT http://localhost:4500/posts/editpost
Content-Type: application/json

{
    "user_id": "39cd9427-42c8-44e1-b436-20612b21d144",
    "post_id": "849aa15d-296f-48d4-af96-86c143058f54",
    "body": "edit post now works, dont touch it",
    "tagged": ""
}


###
#delete a post
PUT http://localhost:4500/posts/deletepost/5c7f8faa-a07e-44da-9094-ea075a391ac9
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4"
}


###
#like post
POST http://localhost:4500/posts/likepost
Content-Type: application/json

{
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "post_id": "c21376b4-56b9-4df1-9428-17eeaf2ac1b2"
}



###
#unlike post
POST http://localhost:4500/posts/unlikepost
Content-Type: application/json

{
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "post_id": "c21376b4-56b9-4df1-9428-17eeaf2ac1b2"
}






###
#comment on post
POST http://localhost:4500/posts/createComment
Content-Type: application/json

{
    "post_id": "c21376b4-56b9-4df1-9428-17eeaf2ac1b2",
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "body": "Success post updated"
}



###
#update comment
POST http://localhost:4500/posts/updateComment
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2OTQ5MzI0NDQsImV4cCI6MTY5NDkzNjA0NH0.JHTl4VlHlKSUIEKoqR2Bom3__de4BmX6DXaGE_qWAOU

{
    "comment_id": "17",
    "post_id": "36750ae1-bdda-4fbe-bae4-005da346fd55",
    "user_id": "b991bde8-ec68-4259-9b4e-f9d76a132ebc",
    "body": "comment sunday test indeed"
}





###
#like comment
POST http://localhost:4500/posts/likeComment
Content-Type: application/json

{
    "user_id": "39cd9427-42c8-44e1-b436-20612b21d144",
    "comment_id": "1"
}



###
#unlike comment
POST http://localhost:4500/posts/unlikeComment
Content-Type: application/json

{
    "user_id": "39cd9427-42c8-44e1-b436-20612b21d144",
    "comment_id": "1"
}




###
#create subcomment 
POST  http://localhost:4500/posts/createSubComment
Content-Type: application/json

{
    "comment_id": "2",
    "user_id": "0edd9c13-d738-42f1-a267-0fedd9a9a8ac",
    "body": "subcomment is under construction"
}



###
#update subcomment 
POST  http://localhost:4500/posts/updateSubcomment
Content-Type: application/json

{
    "subcomment_id": "1",
    "comment_id": "1",
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "body": "subcoment sunday init updated"
}



###
#like sub comment
POST http://localhost:4500/posts/likeSubcomment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "subcomment_id": "1"
}



###
#unlike sub comment
POST http://localhost:4500/posts/unlikeSubcomment
Content-Type: application/json

{
    "user_id": "be6feb2f-4195-40b3-8d65-39403d5f37e4",
    "subcomment_id": "1"
}







# admin controls


###
#barn a user
POST http://localhost:4500/auth/barn
Content-Type: application/json

{
    "admin_id": "b991bde8-ec68-4259-9b4e-f9d76a132ebc",
    "admin_password": "plokijuhy",
    "user_id": "e2793b07-bd4d-42c7-ad97-9dfb122f8ff9"

}


###
#unbarn a user
POST http://localhost:4500/auth/unbarn
Content-Type: application/json

{
    "admin_id": "b991bde8-ec68-4259-9b4e-f9d76a132ebc",
    "admin_password": "plokijuhy",
    "user_id": "e2793b07-bd4d-42c7-ad97-9dfb122f8ff9"

}




// keep email private














